# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg=BASE_IMAGE=gcr.io/cloud-builders/javac:8"
      - "--build-arg=GRADLE_VERSION=6.1"
      - "--build-arg=SHA=d0c43d14e1c70a48b82442f435d06186351a2d290d72afd5b8866f15e6d7038a"
      - "--tag=gcr.io/$PROJECT_ID/gradle:6.1-jdk-8"
      - "--tag=gcr.io/$PROJECT_ID/java/gradle:6.1-jdk-8"
      - "."
    waitFor: ["-"]

  # Tag the default 'latest' version
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "gcr.io/$PROJECT_ID/gradle:6.1-jdk-8"
      - "gcr.io/$PROJECT_ID/java/gradle"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "tag"
      - "gcr.io/$PROJECT_ID/gradle:6.1-jdk-8"
      - "gcr.io/$PROJECT_ID/gradle"

images:
  - "gcr.io/$PROJECT_ID/gradle"
  - "gcr.io/$PROJECT_ID/gradle:6.1-jdk-8"
